### PR TITLE
Sonar Enterprise API

### PR DESCRIPTION
**Pull request by eschellerup**
Hi,

I would like to propose a separate API client for Sonar Enterprise in order not to pollute the CE edition.

NB: The documentation is a duplicate of the Sonar API.

Let me know what you would want to be reworked.

Best regards,

Etienne

### CODE REVIEW

**Comment by shijl0925** [comment]
is these endpoints such as "api/alm_integrations/import_gitlab_project" lost a prefixing slash "/"?

code:
sonarqube/enterprise/alm_integrations.py 
@POST("api/alm_integrations/import_gitlab_project")
def import_gitlab_project(self, almSettings, gitlabProjectId):
    ...

**Comment by eschellerup** [comment]
I believe the url_joiner  function takes care of the prefix slash. I refactored for consistency, adding the slash.

**Comment by shijl0925** [comment]
Thank you for your submit.

**Comment by shijl0925** [comment]
I have released v1.2.1 packge. welcome to use it.

**Pull request merged**
