### PR TITLE
Add support for qualitygates/add_group

### PR DESCRIPTION
**Pull request by samirtahir91**
Hi @shijl0925 

Thanks for all your work on this project

Can we add qualitygates/add_group, it allows us to set group administer permission on individual quality gates as opposed to group global administer quality gate permissions

### CODE REVIEW

**Comment by shijl0925** [comment]
It is unnecessary to provide parameter "organization" for the "api/qualitygates/add_group" API.

**Comment by samirtahir91** [comment]
> It is unnecessary to provide parameter "organization" for the "api/qualitygates/add_group" API.

Have removed now :)

**Comment by samirtahir91** [comment]
Thanks - will there be a new release soon?

**Comment by shijl0925** [comment]
Version 1.3.2 has been released now.

**Comment by samirtahir91** [comment]
> Version 1.3.2 has been released now.

Awesome thanks!

**Pull request merged**
